name: 手動ビルド

on:
    workflow_dispatch:

jobs:
    call-build-main:
        uses: ./.github/workflows/build-main.yml
        secrets: inherit


    upload-artifact:
        runs-on: ubuntu-latest
        needs: [call-build-main]
        steps:
        # - name: upload artifact
        #   uses: actions/upload-artifact@v6
        #   with:
        #       name: build-exe
        #       path: |
        #         ./dist/main
        - name: skip
          run: echo ""
