name: release用

on:
    release:
        types: [published]


permissions:
    # https://github.com/softprops/action-gh-release/issues/572
    contents: write

jobs:
    call-build-main:
        uses: ./.github/workflows/build-main.yml
        secrets: inherit


    upload-asset:
        runs-on: ubuntu-latest
        needs: [call-build-main]
        steps:
        - name: download artifact
          uses: actions/download-artifact@v7
          with:
              name: build-exe
              path: ./build-exe

        #- name: download game
        #  run: |
        #        wget -P ./build-exe/resources/game_win https://web.archive.org/web/20241128191233fw_/https://ftp.vector.co.jp/37/65/1834/nana24.exe

        - name: create 7z archive
          run: |
                ls -al
                sudo apt-get install p7zip-full
                7z a -t7z ./narcissu_gba.7z ./build-exe/* -mx9

        - name: upload asset
          uses: softprops/action-gh-release@v2
          with:
              files: ./narcissu_gba.7z