name: build

on:
    workflow_dispatch:

jobs:
    build-gba:
        runs-on: ubuntu-latest
        container:
            image: devkitpro/devkitarm:20251117
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
            - name: run .build.sh
              run: |
                  chmod +x ./build.sh
                  ./build.sh
                  mv ./src/c/game_core/test.gba ./
                  # mv ./src/c/game_core/hi.gba ./

            - name: upload artifact
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
              with:
                  name: build-gba
                  path: |
                    ./test.gba
                    # ./hi.gba

    build-exe:
        runs-on: windows-latest
        needs: [build-gba]
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

            - name: download artifact
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
              with:
                  name: build-gba
                  path: ./

            - name: setup Python
              uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
              with:
                  python-version: "3.14"
            
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller
                  pip install -r ./src/python/converter/requirements.txt

            - name: build exe
              run: |
                ls ./src/python/converter/
                pyinstaller ./src/python/converter/main.py

            - name: 必要なファイルを移動
              run: |
                mkdir ./dist/main/core_gba
                mv ./test.gba ./dist/main/core_gba/
                # mv ./hi.gba ./dist/main/core_gba/
                mv ./tools ./dist/main/

            - name: upload artifact
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
              with:
                  name: build-exe
                  path: |
                    ./dist/main